### ISSUE TITLE
UnicodeDecode Error

### ISSUE THREAD

**Issue by yashsway** [jayfk/statuspage#102]
Got this problem when I tried to update an issue with a new comment:

```
Traceback (most recent call last):
  File "/Users/yash/.pyenv/versions/2.7.10/bin/statuspage", line 11, in <module>
    sys.exit(cli())
  File "/Users/yash/.pyenv/versions/2.7.10/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/yash/.pyenv/versions/2.7.10/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/yash/.pyenv/versions/2.7.10/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/yash/.pyenv/versions/2.7.10/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/yash/.pyenv/versions/2.7.10/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/yash/.pyenv/versions/2.7.10/lib/python2.7/site-packages/statuspage/statuspage.py", line 73, in update
    run_update(name=name, token=token, org=org)
  File "/Users/yash/.pyenv/versions/2.7.10/lib/python2.7/site-packages/statuspage/statuspage.py", line 211, in run_update
    if is_same_content(content, base64.b64decode(index.content)):
  File "/Users/yash/.pyenv/versions/2.7.10/lib/python2.7/site-packages/statuspage/statuspage.py", line 478, in is_same_content
    return sha1(c1).hexdigest() == sha1(c2).hexdigest()
  File "/Users/yash/.pyenv/versions/2.7.10/lib/python2.7/site-packages/statuspage/statuspage.py", line 476, in sha1
    c = c.encode("utf-8")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 2735: ordinal not in range(128)
```

**Comment by MightyRevenge** [comment]
I am using pyenv by the way and my environment is set to 2.7.10. Three versions are listed when I run 'pyenv versions': system, 2.7.10 and 3.5.1

**Comment by MightyRevenge** [comment]
Funny thing is, it worked for my first initial Issue message. It even had an emoji in it. Then I added another comment to the issue and tried to update. That's when the error started.

**Comment by MightyRevenge** [comment]
This is my python version and LANG environment.
```
Python 2.7.10 (default, Jun 25 2016, 15:13:37) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin

echo $LANG
en_CA.UTF-8
```

**Comment by MightyRevenge** [comment]
Solved temporarily by switching pyenv to 3.5.1. I looked at the code for statuspage.py and after seeing the if statement that handles the python versions decided to try this in version 3+. Looks like for version 2+ the sequence of encoding /decoding must be changed.

**Comment by jayfk** [comment]
> Looks like for version 2+ the sequence of encoding /decoding must be changed.

Yeah, that's why we should keep this open :).

**Comment by martignoni** [comment]
Just getting this error too, with Python 2.7.13.

```
Traceback (most recent call last):
  File "/usr/local/bin/statuspage", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/statuspage/statuspage.py", line 73, in update
    run_update(name=name, token=token, org=org)
  File "/usr/local/lib/python2.7/site-packages/statuspage/statuspage.py", line 211, in run_update
    if is_same_content(content, base64.b64decode(index.content)):
  File "/usr/local/lib/python2.7/site-packages/statuspage/statuspage.py", line 478, in is_same_content
    return sha1(c1).hexdigest() == sha1(c2).hexdigest()
  File "/usr/local/lib/python2.7/site-packages/statuspage/statuspage.py", line 476, in sha1
    c = c.encode("utf-8")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2089: ordinal not in range(128)
```

**Comment by martignoni** [comment]
I can now reproduce the bug:

1. Create a new issue with some UTF8 character in the title and/or the description
2. Update status in the usual way (`statuspage update` in terminal)
3. Update works correctly, and status page displays the issue correctly (with UTF8 chars)
4. Make any issue modification (in the same issue or another) and update status
5. Error occurs
6. Manually edit index.html, changing the UTF8 chars with ASCII chars (e.g. é -> e, à -> a), save file
7. Update status again in the usual way (`statuspage update` in terminal)
8. No error is displayed

So the errors seems to occur when a UTF8 char is present in the index.html file and statuspage.py tries to read it.

Suggested fix: at the beginning of statuspage/statuspage.py, add `unicode_literals` to line `from __future__ import absolute_import, print_function`
