### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 56487: character maps to <undefined>

### ISSUE THREAD

**Issue by Hexexpeck** [jayfk/statuspage#114]
So I was running the command to create a status page (`statuspage create --token=<insert my token here>`)

And during the setup process, it suddenly stopped and gave me this error:
```
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python35-32\Scripts\statuspage-script.py", line 9, in <module>
    load_entry_point('statuspage==0.8.1', 'console_scripts', 'statuspage')()
  File "c:\users\acer\appdata\local\programs\python\python35-32\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\acer\appdata\local\programs\python\python35-32\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\users\acer\appdata\local\programs\python\python35-32\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\acer\appdata\local\programs\python\python35-32\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\acer\appdata\local\programs\python\python35-32\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\users\acer\appdata\local\programs\python\python35-32\lib\site-packages\statuspage\statuspage.py", line 65, in create
    run_create(name=name, token=token, systems=systems, org=org, private=private)
  File "c:\users\acer\appdata\local\programs\python\python35-32\lib\site-packages\statuspage\statuspage.py", line 276, in run_create
    content=f.read(),
  File "c:\users\acer\appdata\local\programs\python\python35-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 56487: character maps to <undefined>
```
I am on a Windows 32 bit machine running Windows 10 and using Python 3.5.0 32 bit.

Please provide some help as soon as possible.
Thank you.

**Comment by MCMiners9** [comment]
I am using the latest version of statuspage (I ran `pip install statuspage --upgrade` and it said Requirement on latest version or something like that)

**Comment by MightyRevenge** [comment]
I don't know if this will help, but update your Python version to 3.5.1

**Comment by MCMiners9** [comment]
Yeah, I tried that but it still fails

**Comment by Hexexpeck** [comment]
Closing issue for no activity/answer
