### ISSUE TITLE
Giving 404 error when running statuspage

### ISSUE THREAD

**Issue by nikolaaa4** [jayfk/statuspage#140]
Hi,

After i ran the script, it outputted me this:
Traceback (most recent call last):
  File "statuspage/statuspage.py", line 352, in <module>
  File "site-packages/click/core.py", line 716, in __call__
  File "site-packages/click/core.py", line 696, in main
  File "site-packages/click/core.py", line 1060, in invoke
  File "site-packages/click/core.py", line 889, in invoke
  File "site-packages/click/core.py", line 534, in invoke
  File "statuspage/statuspage.py", line 54, in create
  File "statuspage/statuspage.py", line 139, in run_create
  File "site-packages/github/PaginatedList.py", line 48, in __iter__
  File "site-packages/github/PaginatedList.py", line 60, in _grow
  File "site-packages/github/PaginatedList.py", line 161, in _fetchNextPage
  File "site-packages/github/Requester.py", line 171, in requestJsonAndCheck
  File "site-packages/github/Requester.py", line 179, in __check
github.GithubException.UnknownObjectException: 404 {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3'}
Failed to execute script statuspage

How can this be fixed?

**Comment by PierreLvx** [comment]
@nikolaaa4 Could you paste the command you used here ? (Redact the token, of course).

**Comment by nikolaaa4** [comment]
Hi,

Tried again using the instructions in readme using pip, now outputting this.
Traceback (most recent call last):
  File "/usr/local/bin/statuspage", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/statuspage/statuspage.py", line 65, in create
    run_create(name=name, token=token, systems=systems, org=org, private=private)
  File "/usr/local/lib/python2.7/dist-packages/statuspage/statuspage.py", line 281, in run_create
    repo.edit(name=name, default_branch="gh-pages")
  File "/usr/local/lib/python2.7/dist-packages/github/Repository.py", line 1068, in edit
    input=post_parameters
  File "/usr/local/lib/python2.7/dist-packages/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/local/lib/python2.7/dist-packages/github/Requester.py", line 180, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {u'documentation_url': u'https://developer.github.com/v3/repos/#edit', u'message': u'Validation Failed', u'errors': [{u'field': u'default_branch', u'message': u'The branch gh-pages was not found. Please push that ref first or create it via the Git Data API.', u'code': u'invalid', u'resource': u'Repository'}]}

**Comment by nikolaaa4** [comment]
Edit: Finally got it to work by deleting my repositories and re-creating them, thanks.
