### ISSUE TITLE
Error while creating status

### ISSUE THREAD

**Issue by HasanBrandsXD** [jayfk/statuspage#180]
```Deleting initial labels: 100%|###########################################################| 7/7 [00:07<00:00,  1.06s/it]
Creating status labels: 100%|############################################################| 3/3 [00:03<00:00,  1.03s/it]
Creating system labels: 100%|############################################################| 4/4 [00:04<00:00,  1.02s/it]
Adding template files:  50%|##############################5                              | 2/4 [00:03<00:03,  1.88s/it]
Traceback (most recent call last):
  File "C:\Users\tdmfa\AppData\Local\Programs\Python\Python35\Scripts\statuspage-script.py", line 9, in <module>
    load_entry_point('statuspage==0.8.1', 'console_scripts', 'statuspage')()
  File "c:\users\tdmfa\appdata\local\programs\python\python35\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\tdmfa\appdata\local\programs\python\python35\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\tdmfa\appdata\local\programs\python\python35\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\tdmfa\appdata\local\programs\python\python35\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\tdmfa\appdata\local\programs\python\python35\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\tdmfa\appdata\local\programs\python\python35\lib\site-packages\statuspage\statuspage.py", line 65, in create
    run_create(name=name, token=token, systems=systems, org=org, private=private)
  File "c:\users\tdmfa\appdata\local\programs\python\python35\lib\site-packages\statuspage\statuspage.py", line 276, in run_create
    content=f.read(),
  File "c:\users\tdmfa\appdata\local\programs\python\python35\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 56487: character maps to <undefined>

C:\Users\tdmfa>```

**Comment by HasanBrandsXD** [comment]
Uhh

**Comment by HasanBrandsXD** [comment]
It's been 9 months, and still no response oh god

**Comment by Mitch123413** [comment]
Fixed, i booted up a ubuntu vm and it works

**Comment by HasanBrandsXD** [comment]
Thank you!
