### ISSUE TITLE
Help. Error on creation.

### ISSUE THREAD

**Issue by Mitch123413** [jayfk/statuspage#224]
Traceback (most recent call last):
  File "C:\Users\phili\AppData\Local\Programs\Python\Python36\Scripts\statuspage-script.py", line 11, in <module>
    load_entry_point('statuspage==0.8.1', 'console_scripts', 'statuspage')()
  File "c:\users\phili\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\phili\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\phili\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\phili\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\phili\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\phili\appdata\local\programs\python\python36\lib\site-packages\statuspage\statuspage.py", line 65, in create
    run_create(name=name, token=token, systems=systems, org=org, private=private)
  File "c:\users\phili\appdata\local\programs\python\python36\lib\site-packages\statuspage\statuspage.py", line 276, in run_create
    content=f.read(),
  File "c:\users\phili\appdata\local\programs\python\python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 56487: character maps to <undefined>

**Comment by mrrsm** [comment]
This is a dupe (though an earlier issue number) of #264 
See the PR from issue #264 it may resolve this issue.

**Comment by MitchellPT** [comment]
> This is a dupe (though an earlier issue number) of #264
> See the PR from issue #264 it may resolve this issue.

This was 2018...
